name: MurderMystery
main: MurderMystery
authors: [Pepej, Tigerpanzer, montlikadani]
version: ${project.version}
api-version: 1.12
depend: [HolographicDisplays]
softdepend: [CorpseReborn, PlaceholderAPI, LeaderHeads, Vault]

commands:
  MurderMystery:
    description: Murder mystery commands
    usage: "\u00A76Correct usage: /mm [stats/leave/join]"
    aliases: [mm, murder]
  MurderMysteryAdmin:
    description: Murder mystery admin commands
    usage: "\u00A76Correct usage: /mma [option]"
    aliases: [mma, murderadmin]

permissions:
  murder.vip:
    description: none
  murder.grand:
    description: none
  murder.premium:
    description: none
  murdermystery.admin.*:
    default: op
    children:
      murdermystery.updatenotify: true
      murdermystery.command.override: true
      murdermystery.admin: true
      murdermystery.admin.setup: true
      murdermystery.admin.create: true
      murdermystery.admin.delete: true
      murdermystery.admin.list: true
      murdermystery.admin.stopgame: true
      murdermystery.admin.forcestart: true
      murdermystery.admin.addsign: true
      murdermystery.admin.sign.create: true
      murdermystery.admin.sign.break: true
      murdermystery.admin.add: true